# --- Welcome ---
# message "Welcome, Danger."

# --- PR title ---
warn "MR is classed as Work in Progress" if gitlab.mr_title.include? "[WIP]"

# --- diff size ---
warn "We cannot handle the scale of this PR" if git.lines_of_code > 500

# --- Label ---
warn "Please add labels to this MR" if gitlab.mr_labels.empty?

# --- Assignee ---
warn "This MR does not have any assignees yet." unless gitlab.mr_json["assignee"]

# --- Swiftlint ---
swiftlint.config_file = '.swiftlint.yml'
swiftlint.lint_files inline_mode: true
swiftlint.lint_files fail_on_error: true

