# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'cocoapods',	'~> 1.9'
gem 'xcpretty', 	'~> 0.3'
gem 'fastlane',		'~> 2'
gem 'danger-gitlab',	'~> 8.0'
gem 'danger-swiftlint',	'~> 0.24'
gem 'jazzy',		'~> 0.13'
gem 'generamba',	'~> 1.5'
gem 'rake',		'~> 13.0'
gem 'slather',		'~> 2.5'
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
